var gulp = require('gulp');
//var coffee = require('gulp-coffee');
var concat = require('gulp-concat');
var dest = require('gulp-dest');
var uglify = require('gulp-uglify');
var checkFilesize = require("gulp-check-filesize");
var del = require('del');
var sizereport = require('gulp-sizereport');
var debug = require('gulp-debug');

var newer = require('gulp-newer');

var extVersion = '4.2.0';

/*
 * !! IMPORTANT
 * collectionNames and collectorLookup are closely related since
 * foreach item on collectionNames there is an array into collectorLookup
 * 
 */
var collectionPath = 'cmdbuild/collection';
var collectionNames = ['libs.min.js', 'main.min.js', 'core.min.js', 'management.min.js', 'bim.min.js', 'app.min.js', 'runtime.min.js'];
var collectorLookup = [
                       
                       // lib JS
	                   ['ext-'+ extVersion+'/ext-all.js',
	                    'log/log4javascript.js',
						'ext-'+ extVersion+'-ux/grid/CheckColumn.js',
						'ext-'+ extVersion+'-ux/event/Broadcast.js',
						'ext-'+ extVersion+'-ux/form/ColorField.js',
						'ext-'+ extVersion+'-ux/form/MultiSelect.js',
						'ext-'+ extVersion+'-ux/form/XCheckbox.js',
						'ext-'+ extVersion+'-ux/form/XCombo.js',
						'ext-'+ extVersion+'-ux/Notification.js',
						'ext-'+ extVersion+'-ux/Router.js',
						'ext-'+ extVersion+'-ux/plugins/TreeEditing.js',
						'extensible-1.5.1/src/calendar/data/EventMappings.js',
						'extensible-1.5.1/src/calendar/data/EventModel.js',
						'ext-'+ extVersion+'-ux/portal/Portlet.js',
						'ext-'+ extVersion+'-ux/portal/PortalDropZone.js',
						'ext-'+ extVersion+'-ux/portal/PortalColumn.js',
						'ext-'+ extVersion+'-ux/portal/PortalPanel.js',
						'extensible-1.5.1/lib/extensible-all.js',
						'ext-'+ extVersion+'-ux/PatchOverride.js'
						//'ext-'+ extVersion+'-ux/form/field/tinymce/tiny_mce.js'
						],
					   // main JS
					   ['cmdbuild/core/constants/Proxy.js',
						'cmdbuild/core/LoaderConfig.js',
						'cmdbuild/core/Utils.js',
						'log/log4javascript.js', //redundant!!
						'cmdbuild/core/interfaces/Ajax.js',
						'cmdbuild/core/Message.js',
						'cmdbuild/core/CookiesManager.js',
						'cmdbuild/core/configurations/DataFormat.js',],
					   // core JS	 
					   ['cmdbuild/core/LoaderConfig.js',
					    'cmdbuild/core/Data.js',
						'cmdbuild/core/Utils.js',
						'cmdbuild/override/data/proxy/Server.js',
						'cmdbuild/override/data/SortTypes.js',
						'cmdbuild/override/data/Store.js',
						'cmdbuild/override/data/TreeStore.js',
						'cmdbuild/override/form/field/Checkbox.js',
						'cmdbuild/override/form/field/ComboBox.js',
						'cmdbuild/override/form/field/Display.js',
						'cmdbuild/override/form/field/File.js',
						'cmdbuild/override/form/field/VTypes.js',
						'cmdbuild/override/form/FieldContainer.js',
						'cmdbuild/override/form/FieldSet.js',
						'cmdbuild/override/grid/column/CheckColumn.js',
						'cmdbuild/override/grid/plugin/RowExpander.js',
						'cmdbuild/override/JSON.js',
						'cmdbuild/override/layout/container/Editor.js',
						'cmdbuild/override/selection/CheckboxModel.js',
						'cmdbuild/override/toolbar/Paging.js',
						'cmdbuild/core/configurations/DataFormat.js',
						'cmdbuild/model/report/Cache.js',
						'cmdbuild/model/CMCacheModels.js',
						'cmdbuild/model/CMFilterModel.js',
						'cmdbuild/model/CMDashboardModels.js',
						'cmdbuild/selection/CMMultiPageSelectionModel.js',
						'cmdbuild/cache/CMCacheFilterFunctions.js',
						'cmdbuild/cache/CMCacheClassFunctions.js',
						'cmdbuild/cache/CMCacheLookupFunctions.js',
						'cmdbuild/cache/CMCacheDomainFunctions.js',
						'cmdbuild/cache/CMCacheDashboardFunctions.js',
						'cmdbuild/cache/CMCacheGISFunctions.js',
						'cmdbuild/cache/CMCache.js',
						'cmdbuild/controller/common/TemplateResolver.js',
						'cmdbuild/core/interfaces/Ajax.js',
						'cmdbuild/core/CMDelegable.js',
						'cmdbuild/core/xml/XMLUtility.js',
						'cmdbuild/form/CallbackPlugin.js',
						'cmdbuild/form/CustomVTypes.js',
						'cmdbuild/form/FormOverride.js',
						'cmdbuild/form/FormPlugin.js',
						'cmdbuild/form/HexColorField.js',
						'cmdbuild/form/RangeSliders.js',
						'cmdbuild/form/SetValueOnLoadPlugin.js',
						'cmdbuild/view/management/common/widgetBuilders/BaseAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/SimpleQueryAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/RangeQueryAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/TextualQueryAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/DecimalAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/DoubleAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/IntegerAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/IPAddressAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/DateAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/TimeStampAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/TimeAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/BooleanAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/ComboAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/LookupAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/ReferenceAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/ForeignKeyAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/StringAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/CharAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/CustomListAttribute.js',
						'cmdbuild/view/management/common/widgetBuilders/TextAttribute.js',
						'cmdbuild/view/common/field/CMBaseCombo.js',
						'cmdbuild/view/common/field/CMErasableCombo.js',
						'cmdbuild/view/common/field/CMGroupSelectionList.js',
						'cmdbuild/view/common/field/FieldManager.js',
						'cmdbuild/view/common/field/BooleanDisplayField.js',
						'cmdbuild/view/common/field/CMDisplayField.js',
						'cmdbuild/view/common/field/HtmlEditor.js',
						'cmdbuild/view/common/field/LookupField.js',
						'cmdbuild/view/common/field/GridSearchField.js',
						'cmdbuild/view/common/field/LocaleSearchField.js',
						'cmdbuild/view/common/field/SearchableCombo.js',
						'cmdbuild/view/common/field/CMToggleButtonToShowReferenceAttributes.js',
						'cmdbuild/view/common/field/ReferenceField.js',
						'cmdbuild/view/common/field/ForeignKeyField.js',
//						'cmdbuild/delegate/common/filter/CMFilterMenuButtonDelegate.js',
						'cmdbuild/view/common/CMUnconfiguredModPanel.js',
						'cmdbuild/view/common/CMFormFuncions.js',
						'cmdbuild/view/management/common/CMCardGrid.js',
						'cmdbuild/view/management/common/CMCardListWindow.js',
						'cmdbuild/view/management/common/CMReferenceSearchWindow.js',
						
						'cmdbuild/view/management/common/filter/CMFilterMenuButton.js',
						'cmdbuild/view/management/common/filter/CMRuntimeParameterWindowField.js',
						'cmdbuild/view/management/common/filter/CMRuntimeParameterWindowDelegate.js',
						'cmdbuild/view/management/common/filter/CMFilterMenuButtonPicker.js',
						
//						'cmdbuild/view/management/common/filter/CMFilterWindow.js',
						'cmdbuild/view/common/filter/CMFilterConfigurationWindow.js',
						'cmdbuild/view/management/common/filter/CMFilterAttribute.js',
						'cmdbuild/controller/management/common/CMCardGridController.js',
						'cmdbuild/view/management/common/filter/relations/CMDomainGrid.js',
						'cmdbuild/view/management/common/filter/CMFilterRelation.js',
						'cmdbuild/view/management/common/filter/CMFilterFunction.js',
						'cmdbuild/view/common/filter/CMFilterChooser.js',
						'cmdbuild/view/common/chart/CMChartPortletForm.js',
						'cmdbuild/view/common/chart/CMChartPortlet.js',
						'cmdbuild/controller/common/CMBasePanelController.js',
						'cmdbuild/controller/common/CMUnconfiguredModPanelController.js',
						'cmdbuild/controller/management/classes/StaticsController.js',
						'cmdbuild/controller/common/CMDashboardColumnController.js',
						'cmdbuild/controller/common/chart/CMChartPortletController.js',
						'cmdbuild/bim/package.js',
						'cmdbuild/bim/data/CMBIMProjectModel.js',
						'cmdbuild/bim/data/CMBimLayerModel.js'],
					   // management JS
					   ['cmdbuild/selection/CMMultiPageSelectionModel.js',
						'cmdbuild/state/CMWorkflowState.js',
						'cmdbuild/state/CMUIState.js',
						'cmdbuild/state/CMCardModuleState.js',
						'cmdbuild/model/widget/CMWidgetReaders.js',
						'cmdbuild/data/CMMiniCardGridBaseDataSource.js',
						'cmdbuild/data/CMDetailedCardDataSource.js',
						'cmdbuild/view/management/common/CMEditablePanel.js',
						'cmdbuild/view/management/common/CMSideTabPanel.js',
						'cmdbuild/view/management/common/CMTabPanel.js',
						'cmdbuild/view/management/common/CMMiniCardGrid.js',
						'cmdbuild/view/management/common/CMMiniCardGridWindow.js',
						'cmdbuild/view/management/common/CMCardWindow.js',
						'cmdbuild/view/management/common/CMCardListWindow.js',
						'cmdbuild/view/management/common/CMReferenceSearchWindow.js',
						'cmdbuild/view/management/common/widgets/CMWidgetManager.js',
						'cmdbuild/view/management/common/CMCardForm.js',
						'cmdbuild/view/management/classes/CMCardNotesPanel.js',
						'cmdbuild/view/management/classes/relations/CMCardRelationsPanel.js',
						'cmdbuild/view/management/common/widgets/CMWidgetsWindow.js',
						'cmdbuild/view/management/common/widgets/CMWidgetButtonsPanel.js ',
						'cmdbuild/view/management/common/widgets/CMFormWithWidgetButtons.js',
						'cmdbuild/view/management/common/widgets/CMCalendar.js',
						'cmdbuild/view/management/common/widgets/CMWebService.js',
						'cmdbuild/view/management/common/widgets/CMPresetFromCard.js',
						'cmdbuild/view/management/classes/CMModCard.js',
						'cmdbuild/view/management/classes/CMCardPanel.js',
						'cmdbuild/view/management/classes/CMCardTabPanel.js',
						'cmdbuild/view/management/classes/relations/CMEditRelationWindow.js"',
						'cmdbuild/view/management/classes/masterDetails/CMMasterDetailGrid.js',
						'cmdbuild/view/management/classes/masterDetails/CMCardMasterDetail.js',
						'cmdbuild/view/management/dashboard/CMModDashbaord.js',
						'cmdbuild/controller/management/classes/CMModCardSubController.js',
						'cmdbuild/controller/management/common/CMModClassAndWFCommons.js',
						'cmdbuild/controller/management/common/CMCardBrowserTreeDataSource.js',
						'cmdbuild/controller/management/classes/CMBaseCardPanelController.js',
						'cmdbuild/controller/management/classes/CMRelationsController.js',
						'cmdbuild/controller/management/classes/CMMasterDetailsController.js',
						'cmdbuild/controller/management/classes/CMNoteController.js',
						'cmdbuild/view/management/classes/map/CMMapPanel.js',
						'cmdbuild/view/management/classes/map/MapEditingWindow.js',
						'cmdbuild/controller/management/common/widgets/CMWidgetController.js',
						'cmdbuild/controller/management/common/widgets/CMCalendarController.js',
						'cmdbuild/controller/management/common/widgets/CMWebServiceController.js',
						'cmdbuild/controller/management/common/widgets/CMPresetFromCardController.js',
						'cmdbuild/controller/management/common/widgets/CMWidgetManagerController.js',
						'cmdbuild/controller/management/dashboard/CMModDashboardController.js',
						'cmdbuild/controller/management/classes/CMModCardController.js',
						'cmdbuild/controller/management/classes/CMCardPanelController.js',
						'cmdbuild/controller/management/common/CMCardWindowController.js',
						'cmdbuild/controller/management/common/CMDetailWindowController.js',
						'cmdbuild/controller/management/common/CMAddDetailWindowController.js'],
					   // bim JS	
					   [
					    'cmdbuild/bim/surfer/lib/scenejs.js',
					    'cmdbuild/bim/surfer/lib/bimviews.js',
					    'cmdbuild/bim/surfer/JQuery/jquery-2.1.4.min.js',
					    'cmdbuild/bim/surfer/JQuery/jquery.cookie.min.js',
					    'cmdbuild/bim/surfer/lib/bimserverapi.js',
					    'cmdbuild/bim/surfer/lib/bimsurfer.js',
					    'cmdbuild/bim/surfer/CMClasses/PreloadQuery.js',
					    'cmdbuild/bim/surfer/CMClasses/SceneTree.js',
					    'cmdbuild/bim/surfer/CMClasses/IfcTree.js',
					    'cmdbuild/bim/surfer/CMClasses/ProjectLoader.js',
					    'cmdbuild/bim/surfer/Viewer.js',
					    'cmdbuild/bim/management/view/CMBimControlPanel.js',
					    'cmdbuild/bim/management/view/CMBimPlayerLayers.js',
					    'cmdbuild/bim/management/view/CMCardDataWindow.js',
					    'cmdbuild/bim/management/view/CMBimTree.js',
					    'cmdbuild/bim/management/view/CMBimWindow.js',
					    'cmdbuild/bim/management/controller/CMBimController.js'
					    ],
		 				// app JS
		 				['cmdbuild/core/constants/Global.js',
		 				'cmdbuild/core/CookiesManager.js',
		 				'cmdbuild/core/interfaces/messages/Error.js',
		 				'cmdbuild/core/interfaces/messages/Warning.js',
		 				'cmdbuild/core/interfaces/service/LoadMask.js',
		 				'cmdbuild/proxy/Cache.js',
		 				'cmdbuild/proxy/common/tabs/attribute/Attribute.js',
		 				'cmdbuild/proxy/gis/Layer.js',
		 				'cmdbuild/proxy/index/Json.js',
		 				'cmdbuild/proxy/TemplateResolver.js',
		 				'cmdbuild/proxy/Card.js',
		 				'cmdbuild/core/constants/FieldWidths.js',
		 				'cmdbuild/view/common/field/CMBaseCombo.js',
		 				'cmdbuild/proxy/common/field/multiselect/Group.js',
		 				'ext-'+ extVersion+'-ux/form/field/TinyMCE.js',
		 				'cmdbuild/view/common/field/CMErasableCombo.js',
		 				'cmdbuild/view/common/field/SearchableCombo.js',
		 				'cmdbuild/core/window/AbstractModal.js',
		 				'cmdbuild/view/management/common/CMCardListWindow.js',
		 				'cmdbuild/core/templateResolver/Utils.js',
		 				'cmdbuild/proxy/Filter.js',
		 				'cmdbuild/proxy/dashboard/Chart.js',
		 				'cmdbuild/view/management/common/widgets/CMWidgetsWindow.js',
		 				'cmdbuild/view/management/common/CMCardGrid.js',
		 				'cmdbuild/proxy/management/classes/tabs/MasterDetail.js',
		 				'cmdbuild/proxy/gis/Gis.js',
		 				'cmdbuild/proxy/Relation.js',
		 				'cmdbuild/proxy/management/classes/tabs/Note.js',
		 				'cmdbuild/controller/management/classes/map/CardGrid.js',
		 				'cmdbuild/controller/management/classes/map/LayerTree.js',
		 				'cmdbuild/view/management/classes/map/navigationTree/ViewTree.js',
		 				'cmdbuild/controller/management/classes/map/thematism/ThematismMainWindow.js',
		 				'cmdbuild/view/management/classes/map/thematism/ThematicDocument.js',
		 				'cmdbuild/view/management/classes/map/thematism/ThematicStrategiesManager.js',
		 				'cmdbuild/view/management/classes/map/geoextension/CMDBuildGeoExt.js',
		 				'cmdbuild/view/management/classes/map/thematism/ThematicColors.js',
		 				'cmdbuild/proxy/management/widget/Calendar.js',
		 				'cmdbuild/proxy/widget/WebService.js',
		 				'cmdbuild/controller/management/common/widgets/workflow/CMWorkflowController.js',
		 				'cmdbuild/controller/management/widget/linkCards/LinkCardsController.js',
		 				'cmdbuild/controller/management/widget/manageRelation/CMManageRelationController.js',
		 				'cmdbuild/core/configurations/Timeout.js',
		 				'cmdbuild/proxy/administration/userAndGroup/group/tabs/DefaultFilters.js',
		 				'cmdbuild/controller/management/classes/CMBaseCardPanelController.js',
		 				'cmdbuild/controller/management/common/CMCardWindowController.js',
		 				'cmdbuild/controller/management/common/CMDetailWindowController.js',
		 				'cmdbuild/bim/proxy/Bim.js',
		 				'cmdbuild/controller/management/routes/Card.js',
		 				'cmdbuild/controller/management/routes/Classes.js',
		 				'cmdbuild/controller/management/routes/Instance.js',
		 				'cmdbuild/controller/management/routes/Workflow.js',
		 				'cmdbuild/core/Management.js',
		 				'cmdbuild/core/LoadMask.js',
		 				'cmdbuild/model/common/field/multiselect/Group.js',
		 				'ext-'+ extVersion+'-ux/form/field/TinyMCEWindowManager.js',
		 				'cmdbuild/core/constants/TemplateResolver.js',
		 				'cmdbuild/controller/common/abstract/Base.js',
		 				'cmdbuild/view/management/classes/map/CardGrid.js',
		 				'cmdbuild/view/management/classes/map/LayerTree.js',
		 				'cmdbuild/view/management/classes/map/thematism/ThematismMainWindow.js',
		 				'cmdbuild/view/management/classes/map/proxy/Functions.js',
		 				'cmdbuild/controller/management/common/widgets/workflow/StaticsController.js',
		 				'cmdbuild/proxy/management/widget/Workflow.js',
		 				'cmdbuild/proxy/management/widget/LinkCards.js',
		 				'cmdbuild/proxy/management/widget/ManageRelation.js',
		 				'cmdbuild/model/administration/userAndGroup/group/defaultFilters/Filter.js',
		 				'cmdbuild/core/interfaces/FormSubmit.js',
		 				'cmdbuild/controller/common/abstract/Routes.js',
		 				'cmdbuild/core/configurations/Routes.js',
		 				'cmdbuild/proxy/management/routes/Card.js',
		 				'cmdbuild/proxy/management/routes/Classes.js',
		 				'cmdbuild/controller/management/workflow/Utils.js',
		 				'cmdbuild/core/constants/WorkflowStates.js',
		 				'cmdbuild/proxy/management/routes/Instance.js',
		 				'cmdbuild/core/constants/ModuleIdentifiers.js',
		 				'cmdbuild/proxy/management/routes/Workflow.js',
		 				'cmdbuild/javascripts/cmdbuild/core/Splash.js',
		 				'cmdbuild/proxy/core/Management.js',
		 				'cmdbuild/proxy/dashboard/Dashboard.js',
		 				'cmdbuild/proxy/lookup/Type.js',
		 				'cmdbuild/proxy/Menu.js',
		 				'cmdbuild/proxy/widget/Widget.js',
		 				'cmdbuild/core/window/AbstractCustomModal.js',
		 				'cmdbuild/core/interfaces/Rest.js',
		 				'cmdbuild/proxy/index/Rest.js',
		 				'cmdbuild/model/lookup/Type.js'],
		 				// runtime JS
		 				['cmdbuild/model/core/configuration/runtime/Runtime.js',
		 				'cmdbuild/core/interfaces/messages/Error.js',
		 				'cmdbuild/core/interfaces/messages/Warning.js',
		 				'cmdbuild/core/interfaces/service/LoadMask.js',
		 				'cmdbuild/core/LoadMask.js',
		 				'cmdbuild/core/Splash.js',
		 				'cmdbuild/core/Routes.js',
		 				/*'cmdbuild/core/LoggerManager.js',
		 				'log/log4javascript.js', */
		 				'cmdbuild/core/interfaces/Init.js',
		 				'cmdbuild/core/interfaces/Configurations.js',
		 				'cmdbuild/core/Data.js',
		 				'cmdbuild/core/cache/Cache.js',
		 				'cmdbuild/core/navigation/Chronology.js',
		 				'cmdbuild/controller/navigation/Chronology.js',
		 				'cmdbuild/controller/navigation/ButtonHandlers.js',
		 				'cmdbuild/core/RequestBarrier.js',
		 				'cmdbuild/model/core/Barrier.js',
		 				'cmdbuild/core/configurations/builder/Instance.js',
		 				'cmdbuild/proxy/core/configurations/builder/Instance.js',
		 				'cmdbuild/model/core/configuration/builder/Instance.js',
		 				'cmdbuild/core/configurations/builder/Bim.js',
		 				'cmdbuild/proxy/core/configurations/builder/Bim.js',
		 				'cmdbuild/model/core/configuration/builder/Bim.js',
		 				'cmdbuild/core/configurations/builder/Dms.js',
		 				'cmdbuild/proxy/core/configurations/builder/Dms.js',
		 				'cmdbuild/model/core/configuration/builder/Dms.js',
						'cmdbuild/core/configurations/builder/Gis.js',
		 				'cmdbuild/proxy/core/configurations/builder/Gis.js',
		 				'cmdbuild/model/core/configuration/builder/gis/Gis.js',
		 				'cmdbuild/model/core/configuration/builder/gis/Geoserver.js',
		 				'cmdbuild/model/core/configuration/builder/gis/Google.js',
		 				'cmdbuild/model/core/configuration/builder/gis/Osm.js',
		 				'cmdbuild/model/core/configuration/builder/gis/Yahoo.js',
		 				'cmdbuild/core/configurations/builder/Localization.js',
		 				'cmdbuild/proxy/administration/configuration/GeneralOptions.js',
		 				'cmdbuild/model/administration/configuration/generalOptions/StartingClass.js',
		 				'cmdbuild/proxy/core/configurations/builder/Localization.js',
		 				'cmdbuild/model/core/configuration/builder/Localization.js',
		 				'cmdbuild/core/configurations/builder/RelationGraph.js',
		 				'cmdbuild/proxy/core/configurations/builder/RelationGraph.js',
		 				'cmdbuild/model/core/configuration/builder/RelationGraph.js',
		 				'cmdbuild/core/configurations/builder/UserInterface.js',
		 				'cmdbuild/proxy/core/configurations/builder/UserInterface.js',
		 				'cmdbuild/model/core/configuration/builder/userInterface/UserInterface.js',
		 				'cmdbuild/model/core/configuration/builder/userInterface/DisabledCardTabs.js',
		 				'cmdbuild/model/core/configuration/builder/userInterface/DisabledModules.js',
		 				'cmdbuild/model/core/configuration/builder/userInterface/DisabledProcessTabs.js',
						'cmdbuild/core/configurations/builder/Workflow.js',
		 				'cmdbuild/proxy/core/configurations/builder/Workflow.js',
		 				'cmdbuild/model/core/configuration/builder/Workflow.js',
		 				'cmdbuild/model/localization/Localization.js',
		 				'cmdbuild/model/Cache.js',
		 				'cmdbuild/core/buttons/iconized/split/add/Card.js',
		 				'cmdbuild/core/cache/Store.js',
		 				'cmdbuild/controller/common/panel/gridAndForm/panel/common/filter/advanced/Advanced.js',
		 				'cmdbuild/view/common/panel/gridAndForm/panel/common/filter/advanced/AdvancedView.js',
		 				'cmdbuild/core/buttons/iconized/filter/SearchSet.js',
		 				'cmdbuild/core/buttons/Base.js',
		 				'cmdbuild/core/buttons/iconized/filter/SearchClear.js',
		 				'cmdbuild/controller/common/panel/gridAndForm/panel/common/filter/advanced/Manager.js',
		 				'cmdbuild/proxy/common/panel/gridAndForm/filter/advanced/Manager.js',
		 				'cmdbuild/model/common/panel/gridAndForm/filter/advanced/Filter.js',
		 				'cmdbuild/view/common/panel/gridAndForm/panel/common/filter/advanced/manager/ManagerWindow.js',
		 				'cmdbuild/core/buttons/iconized/add/Add.js',
		 				'cmdbuild/view/common/panel/gridAndForm/panel/common/filter/advanced/manager/GridPanel.js',
		 				'cmdbuild/core/buttons/iconized/Save.js',
		 				'cmdbuild/core/buttons/iconized/Modify.js',
						'cmdbuild/core/buttons/iconized/Clone.js',
						'cmdbuild/core/buttons/iconized/Remove.js',
						'cmdbuild/controller/common/panel/gridAndForm/panel/common/filter/advanced/filterEditor/FilterEditor.js',
						'cmdbuild/view/common/panel/gridAndForm/panel/common/filter/advanced/filterEditor/FilterEditorWindow.js',
						'cmdbuild/core/buttons/text/Apply.js',
						'cmdbuild/core/buttons/text/SaveAndApply.js',
						'cmdbuild/core/buttons/text/Abort.js',
						'cmdbuild/controller/common/panel/gridAndForm/panel/common/filter/advanced/filterEditor/Attributes.js',
						'cmdbuild/proxy/common/panel/gridAndForm/filter/advanced/filterEditor/Attributes.js',
						'cmdbuild/view/common/panel/gridAndForm/panel/common/filter/advanced/filterEditor/attributes/AttributesView.js',
						'cmdbuild/view/common/panel/gridAndForm/panel/common/filter/advanced/filterEditor/attributes/FormPanel.js',
						'cmdbuild/core/buttons/iconized/split/add/Add.js',
						'cmdbuild/controller/common/panel/gridAndForm/panel/common/filter/advanced/filterEditor/relations/Relations.js',
						'cmdbuild/view/common/panel/gridAndForm/panel/common/filter/advanced/filterEditor/relations/RelationsView.js',
						'cmdbuild/controller/common/panel/gridAndForm/panel/common/filter/advanced/filterEditor/relations/GridCard.js',
						/*'cmdbuild/controller/common/panel/gridAndForm/panel/common/filter/advanced/filterEditor/relations/CMCardGridController.js',*/
						'cmdbuild/view/common/panel/gridAndForm/panel/common/filter/advanced/filterEditor/relations/CardGridPanelDelegate.js',
						'cmdbuild/view/common/panel/gridAndForm/panel/common/filter/advanced/filterEditor/relations/CardGridPanel.js',
						'cmdbuild/core/buttons/iconized/split/Print.js',
						'cmdbuild/controller/common/panel/gridAndForm/panel/common/filter/advanced/filterEditor/relations/GridDomain.js',
						'cmdbuild/proxy/common/panel/gridAndForm/filter/advanced/filterEditor/Relations.js',
						'cmdbuild/model/common/panel/gridAndForm/filter/advanced/filterEditor/relations/DestinationEditorStore.js',
						'cmdbuild/model/common/panel/gridAndForm/filter/advanced/filterEditor/relations/DomainGrid.js',
						'cmdbuild/view/common/panel/gridAndForm/panel/common/filter/advanced/filterEditor/relations/DomainGridPanel.js',
						'cmdbuild/controller/common/panel/gridAndForm/panel/common/filter/advanced/SaveDialog.js',
						'cmdbuild/view/common/panel/gridAndForm/panel/common/filter/advanced/saveDialog/SaveDialogWindow.js',
						'cmdbuild/view/common/panel/gridAndForm/panel/common/filter/advanced/saveDialog/FormPanel.js',
						'cmdbuild/view/common/PanelFunctions.js',
						'cmdbuild/view/common/PanelFunctions2.js',
						'cmdbuild/core/buttons/text/Save.js',
						'cmdbuild/core/buttons/iconized/add/Relation.js',
						'cmdbuild/proxy/core/buttons/iconized/add/Relation.js',
						'cmdbuild/core/buttons/iconized/RelationGraph.js',
						'cmdbuild/view/management/classes/tools/Properties.js',
						'cmdbuild/view/management/classes/tools/Menu.js',
						'cmdbuild/view/management/classes/tools/Minimize.js',
						'cmdbuild/view/management/classes/tools/Maximize.js',
						'cmdbuild/view/management/classes/tools/Restore.js',
						'cmdbuild/view/common/panel/gridAndForm/tools/Properties.js',
						'cmdbuild/view/common/panel/gridAndForm/tools/Menu.js',
						'cmdbuild/controller/common/MainViewport.js',
						'cmdbuild/controller/management/accordion/Menu.js',
						'cmdbuild/controller/common/abstract/Accordion.js',
						'cmdbuild/proxy/CustomPage.js',
						'cmdbuild/view/management/accordion/Menu.js',
						'cmdbuild/view/common/abstract/Accordion.js',
						'cmdbuild/model/common/Accordion.js',
						'cmdbuild/model/menu/accordion/Management.js',
						'cmdbuild/controller/management/accordion/Classes.js',
						'cmdbuild/proxy/management/classes/Classes.js',
						'cmdbuild/view/management/accordion/Classes.js',
							
							//error
						//'cmdbuild/controller/management/accordion/DataView.js',
						//'cmdbuild/proxy/dataView/DataView.js',
						//'cmdbuild/view/management/accordion/DataView.js',
						


						 'cmdbuild/controller/management/accordion/Dashboard.js',
						 'cmdbuild/view/management/accordion/Dashboard.js',
						 'cmdbuild/controller/management/accordion/Report.js',
						 'cmdbuild/proxy/report/Report.js',
						 'cmdbuild/model/report/Grid.js',
						 'cmdbuild/view/management/accordion/Report.js',
						 'cmdbuild/model/report/accordion/Management.js',
						 'cmdbuild/controller/management/accordion/CustomPage.js',
						 'cmdbuild/view/management/accordion/CustomPage.js',
						 'cmdbuild/controller/management/accordion/Utility.js',
						 'cmdbuild/view/management/accordion/Utility.js',
						 'cmdbuild/controller/management/customPage/SinglePage.js',
						 'cmdbuild/core/configurations/CustomPage.js',
						 'cmdbuild/view/management/customPage/SinglePagePanel.js',
						
						//error
						//'cmdbuild/controller/management/dataView/DataView.js',
						//'cmdbuild/view/management/dataView/DataViewView.js',
						//'cmdbuild/view/management/dataView/tools/Properties.js',
						//'cmdbuild/view/management/dataView/tools/Menu.js',
						//'cmdbuild/view/management/dataView/tools/Minimize.js',
						//'cmdbuild/view/management/dataView/tools/Maximize.js',
						//'cmdbuild/view/management/dataView/tools/Restore.js',


						 'cmdbuild/controller/management/report/Report.js',
						 'cmdbuild/view/management/report/ReportView.js',
						 'cmdbuild/controller/management/report/Single.js',
						 'cmdbuild/view/management/report/SinglePanel.js',
						 'cmdbuild/core/buttons/fileTypes/Pdf.js',
						 'cmdbuild/core/buttons/fileTypes/Odt.js',
						 'cmdbuild/core/buttons/fileTypes/Rtf.js',
						 'cmdbuild/core/buttons/fileTypes/Csv.js',
						 'cmdbuild/core/buttons/iconized/Download.js',
						 'cmdbuild/controller/management/report/Parameters.js',
						 'cmdbuild/view/management/report/ParametersWindow.js',
						 'cmdbuild/core/buttons/text/Print.js',
						 'cmdbuild/controller/management/utility/Utility.js',
						 'cmdbuild/view/management/utility/UtilityView.js',
						 'cmdbuild/controller/management/workflow/Workflow.js',
						 'cmdbuild/controller/common/panel/gridAndForm/GridAndForm.js',
						 'cmdbuild/controller/common/panel/gridAndForm/panel/mixins/ExpansionMode.js',
						 'cmdbuild/core/constants/Metadata.js',
						 'cmdbuild/proxy/management/workflow/Activity.js',
						 'cmdbuild/proxy/management/workflow/Instance.js',
						 'cmdbuild/proxy/management/workflow/Workflow.js',
						 'cmdbuild/view/management/workflow/WorkflowView.js',
						 'cmdbuild/view/common/panel/gridAndForm/GridAndFormView.js',
						 'cmdbuild/view/common/panel/gridAndForm/tools/Minimize.js',
						 'cmdbuild/view/common/panel/gridAndForm/tools/Maximize.js',
						 'cmdbuild/view/common/panel/gridAndForm/tools/Restore.js',
						 
						 // ERROR
//						 'cmdbuild/controller/management/workflow/panel/form/Form.js',
//						 'cmdbuild/controller/common/panel/gridAndForm/panel/form/Form.js',

						 //'cmdbuild/controller/management/workflow/panel/form/tabs/activity/Activity.js',
						 //'cmdbuild/controller/management/workflow/panel/form/tabs/activity/StaticsController.js',
						 //'cmdbuild/proxy/management/workflow/panel/form/tabs/Activity.js'
						 'cmdbuild/view/management/workflow/panel/form/TabPanel.js',
						 'cmdbuild/controller/management/workflow/panel/form/tabs/activityNew/Tab.js',
						 'cmdbuild/controller/common/panel/module/form/Tab.js',
						 
						 // ERROR
						 //'cmdbuild/view/management/workflow/panel/form/FormPanel.js',
//						 'cmdbuild/view/common/panel/gridAndForm/panel/form/FormPanel.js',
//						 'cmdbuild/view/management/workflow/panel/form/OperativeInstructionsPanel.js',
//						 'cmdbuild/view/management/workflow/panel/form/tabs/activityNew/TabView.js',
//						 'cmdbuild/view/common/panel/module/form/TabView.js',
//						 'cmdbuild/controller/management/workflow/panel/form/tabs/activityNew/panel/Panel.js',
//						 'cmdbuild/controller/common/panel/module/form/panel/Panel.js'
//						 
						 'cmdbuild/controller/common/panel/gridAndForm/panel/mixins/PanelFunctions.js',
						 'cmdbuild/view/common/panel/module/form/panel/PanelView.js',
						 'cmdbuild/controller/management/workflow/panel/form/tabs/activityNew/panel/FieldsTab.js',
						 'cmdbuild/view/common/panel/module/form/panel/FieldsTabPanel.js',
						 'cmdbuild/view/common/panel/gridAndForm/panel/tab/TabPanel.js',
						 'cmdbuild/controller/management/workflow/panel/form/tabs/activityNew/toolbar/Bottom.js',
					 	 'cmdbuild/controller/common/panel/module/form/toolbar/Bottom.js',
					 	 'cmdbuild/controller/common/panel/module/form/toolbar/gridAndForm/Bottom.js',
						 'cmdbuild/view/management/workflow/panel/form/tabs/activityNew/toolbar/BottomView.js',
						 'cmdbuild/view/common/panel/module/form/toolbar/gridAndForm/BottomView.js',
						 'cmdbuild/core/buttons/text/Advance.js',
						 'cmdbuild/controller/management/workflow/panel/form/tabs/activityNew/toolbar/Top.js',
						 'cmdbuild/controller/common/panel/module/form/toolbar/Top.js',
						 'cmdbuild/controller/common/panel/module/form/toolbar/gridAndForm/Top.js',
						 'cmdbuild/view/management/workflow/panel/form/tabs/activityNew/toolbar/TopView.js',
						 'cmdbuild/view/common/panel/module/form/toolbar/TopView.js',
						 'cmdbuild/view/common/panel/module/form/toolbar/gridAndForm/TopView.js',
						 'cmdbuild/controller/management/workflow/panel/form/tabs/activityNew/widget/panel/ButtonGroup.js',
						 'cmdbuild/controller/common/panel/module/widget/panel/ButtonGroup.js',
						 'cmdbuild/view/common/panel/module/widget/panel/ButtonGroupView.js',
						 
						 'cmdbuild/controller/management/workflow/panel/form/tabs/attachment/Attachment.js',
						 'cmdbuild/view/common/panel/module/attachment/TabView.js',
						 'cmdbuild/core/buttons/text/Back.js',
						 'cmdbuild/controller/common/panel/module/attachment/Grid.js',
						 'cmdbuild/proxy/common/panel/module/attachment/Attachment.js',
						 'cmdbuild/model/common/panel/module/attachment/Attachment.js',
						 'cmdbuild/model/common/panel/module/attachment/window/Lookup.js',
						 'cmdbuild/proxy/common/panel/module/attachment/reader/Lookup.js',
						 
//						 'cmdbuild/view/common/panel/module/attachment/GridPanel.js',
//						 'cmdbuild/core/buttons/iconized/Versions.js',
//						 'cmdbuild/controller/common/panel/module/attachment/Versions.js',
//						 'cmdbuild/view/common/panel/module/attachment/versions/VersionsView.js',
//						 'cmdbuild/core/buttons/text/Close.js',
						 //'cmdbuild/view/common/panel/module/attachment/versions/GridPanel.js',
						 //'cmdbuild/proxy/common/panel/module/attachment/Versions.js',
						 //'cmdbuild/controller/common/panel/module/attachment/window/Add.js',						 
						 //'cmdbuild/proxy/common/panel/module/attachment/Add.js'
						 
//						 'cmdbuild/view/common/panel/module/attachment/window/add/AddView.js',
//						 'cmdbuild/core/buttons/text/Confirm.js',
//						 'cmdbuild/view/common/panel/module/attachment/window/add/FormPanel.js',
//						 'cmdbuild/view/common/panel/module/attachment/window/add/ContainerFieldsCommon.js',
//						 'cmdbuild/controller/common/panel/module/attachment/window/container/Metadata.js',
//						 'cmdbuild/view/common/panel/module/attachment/window/container/MetadataView.js'
						 
//						 'cmdbuild/view/common/panel/module/attachment/window/modify/FormPanel.js',
//						 'cmdbuild/view/common/panel/module/attachment/window/modify/ContainerFieldsCommon.js',
//						 'cmdbuild/controller/management/workflow/panel/form/tabs/attachment/Grid.js',
//						 'cmdbuild/view/management/workflow/panel/form/tabs/attachment/GridPanel.js',
//						 'cmdbuild/controller/management/workflow/panel/form/tabs/Email.js',
//						 'cmdbuild/controller/management/common/tabs/email/Email.js',
//						 'cmdbuild/proxy/Utils.js'
//						 'cmdbuild/proxy/email/Template.js',
//						 'cmdbuild/model/email/template/Store.js',
//						 'cmdbuild/controller/management/common/tabs/email/Grid.js',
//						 'cmdbuild/proxy/common/tabs/email/Email.js',
//						 'cmdbuild/model/common/tabs/email/Email.js'
						 
						 
						 'cmdbuild/view/management/common/tabs/email/GridPanel.js',
						 'cmdbuild/core/buttons/email/Regenerate.js',
						 'cmdbuild/core/buttons/iconized/Reload.js',
						 'cmdbuild/core/buttons/email/Reply.js',
						 'cmdbuild/core/buttons/email/Send.js',
						 'cmdbuild/core/buttons/email/Edit.js',
						 'cmdbuild/core/buttons/email/View.js',
						 'cmdbuild/core/buttons/email/Delete.js',
						 'cmdbuild/controller/management/common/tabs/email/EmailWindow.js',
						 'cmdbuild/controller/common/abstract/Widget.js',
						 'cmdbuild/proxy/common/tabs/email/Attachment.js',
						 'cmdbuild/model/common/tabs/email/attachments/Attachment.js',
						 'cmdbuild/model/common/tabs/email/attachments/TargetClass.js',
						 'cmdbuild/controller/management/common/tabs/email/ConfirmRegenerationWindow.js',
						 'cmdbuild/view/management/common/tabs/email/ConfirmRegenerationWindow.js',
						 'cmdbuild/view/management/workflow/panel/form/tabs/email/Email.js',
						 'cmdbuild/view/management/common/tabs/email/EmailView.js',
						 //'cmdbuild/controller/management/workflow/panel/form/tabs/History.js',
						 'cmdbuild/proxy/management/workflow/panel/form/tabs/History.js',
						 'cmdbuild/model/management/workflow/panel/form/tabs/history/CardRecord.js',
						 'cmdbuild/view/management/workflow/panel/form/tabs/history/HistoryView.js',
						 'cmdbuild/view/management/workflow/panel/form/tabs/history/GridPanel.js',
						 'cmdbuild/view/management/workflow/panel/form/tabs/history/RowExpander.js',
						 'cmdbuild/controller/management/workflow/panel/form/tabs/Note.js',
						 'cmdbuild/proxy/management/workflow/panel/form/tabs/Note.js',
						 'cmdbuild/view/management/workflow/panel/form/tabs/note/NoteView.js',
//						 'cmdbuild/controller/management/workflow/panel/form/tabs/Relations.js',
//						 'cmdbuild/proxy/management/workflow/panel/form/tabs/Relations.js',
//						 'cmdbuild/view/management/workflow/panel/form/tabs/relations/RelationsView.js',
						 'cmdbuild/controller/common/panel/module/attachment/Window.js',
						 'cmdbuild/proxy/common/panel/module/attachment/Window.js',
						 'cmdbuild/view/common/panel/module/attachment/WindowView.js',
						 'cmdbuild/controller/management/workflow/panel/tree/Tree.js',
						 'cmdbuild/controller/common/panel/gridAndForm/panel/tree/Tree.js',
						 'cmdbuild/proxy/management/workflow/panel/tree/Tree.js',
						 'cmdbuild/model/management/workflow/Node.js',
						 'cmdbuild/proxy/management/workflow/panel/tree/Reader.js',
						 'cmdbuild/view/management/workflow/panel/tree/TreePanel.js',
						 'cmdbuild/view/common/panel/gridAndForm/panel/tree/TreePanel.js',
						 'cmdbuild/proxy/common/panel/gridAndForm/Print.js',
						 'cmdbuild/view/common/panel/gridAndForm/panel/common/print/WindowView.js',
						 'cmdbuild/controller/common/field/filter/runtimeParameters/RuntimeParameters.js',
						 'cmdbuild/proxy/common/field/filter/RuntimeParameters.js',
						 'cmdbuild/view/common/field/filter/runtimeParameters/RuntimeParametersWindow.js',
						 'cmdbuild/controller/management/workflow/panel/tree/toolbar/Paging.js',
						 'cmdbuild/controller/common/field/filter/basic/Basic.js',
						 'cmdbuild/view/common/field/filter/basic/Basic.js',
						 'cmdbuild/controller/management/workflow/panel/tree/filter/advanced/Advanced.js',
						 'cmdbuild/view/management/workflow/panel/tree/filter/advanced/AdvancedView.js',
						 'cmdbuild/controller/management/workflow/panel/tree/filter/advanced/Manager.js',
						 'cmdbuild/proxy/management/workflow/panel/tree/filter/advanced/Manager.js',
						 'cmdbuild/controller/common/field/filter/basic/Basic.js',
						 'cmdbuild/view/common/field/filter/basic/Basic.js',
						 'cmdbuild/controller/management/workflow/panel/tree/filter/advanced/Advanced.js',
						 'cmdbuild/view/management/workflow/panel/tree/filter/advanced/AdvancedView.js',
						 'cmdbuild/controller/management/workflow/panel/tree/filter/advanced/Manager.js',
						 'cmdbuild/proxy/management/workflow/panel/tree/filter/advanced/Manager.js',
						 'cmdbuild/model/management/workflow/panel/tree/filter/advanced/Filter.js',
						 'cmdbuild/view/management/workflow/panel/tree/filter/advanced/manager/ManagerWindow.js',
						 'cmdbuild/view/management/workflow/panel/tree/filter/advanced/manager/GridPanel.js',
		 				 'cmdbuild/controller/management/workflow/panel/tree/filter/advanced/filterEditor/FilterEditor.js',
		 				 'cmdbuild/view/management/workflow/panel/tree/filter/advanced/filterEditor/FilterEditorWindow.js',
		 				 'cmdbuild/controller/management/workflow/panel/tree/filter/advanced/filterEditor/Attributes.js',
		 				 'cmdbuild/proxy/management/workflow/panel/tree/filter/advanced/filterEditor/Attributes.js',
		 				 'cmdbuild/view/management/workflow/panel/tree/filter/advanced/filterEditor/attributes/AttributesView.js',
		 				 'cmdbuild/view/management/workflow/panel/tree/filter/advanced/filterEditor/attributes/FormPanel.js',
		 				 'cmdbuild/controller/management/workflow/panel/tree/filter/advanced/filterEditor/relations/Relations.js',
		 				 'cmdbuild/view/management/workflow/panel/tree/filter/advanced/filterEditor/relations/RelationsView.js',
		 				 'cmdbuild/controller/management/workflow/panel/tree/filter/advanced/filterEditor/relations/GridCard.js',
		 				 //'cmdbuild/controller/management/workflow/panel/tree/filter/advanced/filterEditor/relations/CMCardGridController.js',
		 				 'cmdbuild/view/management/workflow/panel/tree/filter/advanced/filterEditor/relations/CardGridPanelDelegate.js',
		 				 'cmdbuild/view/management/workflow/panel/tree/filter/advanced/filterEditor/relations/CardGridPanel.js',
		 				 'cmdbuild/controller/management/workflow/panel/tree/filter/advanced/filterEditor/relations/GridDomain.js',
		 				 'cmdbuild/proxy/management/workflow/panel/tree/filter/advanced/filterEditor/Relations.js',
		 				 'cmdbuild/model/management/workflow/panel/tree/filter/advanced/filterEditor/relations/DestinationEditorStore.js',
		 				 'cmdbuild/model/management/workflow/panel/tree/filter/advanced/filterEditor/relations/DomainGrid.js',
		 				 'cmdbuild/view/management/workflow/panel/tree/filter/advanced/filterEditor/relations/DomainGridPanel.js',
		 				 'cmdbuild/controller/management/workflow/panel/tree/filter/advanced/SaveDialog.js',
		 				 'cmdbuild/view/management/workflow/panel/tree/filter/advanced/saveDialog/SaveDialogWindow.js',
		 				 'cmdbuild/view/management/workflow/panel/tree/filter/advanced/saveDialog/FormPanel.js',
		 				 'cmdbuild/view/management/workflow/panel/tree/toolbar/Paging.js',
		 				 'cmdbuild/controller/management/workflow/panel/tree/toolbar/Top.js',
		 				 'cmdbuild/view/management/workflow/panel/tree/toolbar/TopView.js',
		 				 'cmdbuild/core/buttons/iconized/add/Workflow.js',
		 				 'cmdbuild/controller/management/classes/panel/form/tabs/card/Tab.js',
		 				 'cmdbuild/proxy/management/classes/panel/form/tabs/Card.js',
		 				 'cmdbuild/view/management/classes/panel/form/tabs/card/TabView.js',
		 				 'cmdbuild/controller/management/classes/panel/form/tabs/card/panel/Panel.js',
		 				 'cmdbuild/controller/management/classes/panel/form/tabs/card/toolbar/Bottom.js',
		 				 'cmdbuild/view/common/panel/module/form/toolbar/BottomView.js',
		 				 'cmdbuild/controller/management/classes/panel/form/tabs/card/toolbar/Top.js',
		 				 'cmdbuild/view/management/classes/panel/form/tabs/card/toolbar/TopView.js',
		 				 'cmdbuild/controller/management/classes/panel/form/tabs/card/widget/panel/ButtonGroup.js',
		 				 'cmdbuild/controller/management/classes/common/attachment/Window.js',
		 				 'cmdbuild/controller/management/classes/panel/form/tabs/masterDetail/window/Note.js',
		 				 'cmdbuild/proxy/management/classes/panel/form/tabs/masterDetail/window/Note.js',
		 				 'cmdbuild/view/management/classes/panel/form/tabs/masterDetail/window/NoteView.js',
		 				 'cmdbuild/javascripts/cmdbuild/controller/management/classes/tabs/History.js',
		 				 'cmdbuild/proxy/management/classes/tabs/History.js',
		 				 'cmdbuild/model/classes/tabs/history/CardRecord.js',
		 				 'cmdbuild/view/management/classes/tabs/history/HistoryView.js',
		 				 'cmdbuild/view/management/classes/tabs/history/GridPanel.js',
		 				 'cmdbuild/view/management/classes/tabs/history/RowExpander.js',
		 				 
		 				 'cmdbuild/controller/management/classes/tabs/Email.js',
		 				 'cmdbuild/controller/management/classes/panel/form/tabs/Attachment.js',
		 				 'cmdbuild/model/common/tabs/email/SelectedEntity.js',
		 				 'cmdbuild/view/common/MainViewport.js',
		 				 'cmdbuild/model/navigation/chronology/Record.js',
		 				 'cmdbuild/model/navigation/chronology/RecordProperty.js'
						 
						 
						 ]
	                 ];


gulp.task('clean', function() {
	return del(collectionPath);
});

//disabled 'clean' task, to allow incremental (fast) build; clean will be run from maven when invoked with 'mvn clean'
//with 'newer' plugin only modified files will be rebuilt (when running incremental build)

//gulp.task('default',['clean'], function() { 
gulp.task('default', function() { 
  for(var c in collectorLookup) {
	  
	  var stream = gulp.src(collectorLookup[c])
		.pipe(newer(collectionPath + '/' + collectionNames[c]))
	    .pipe(concat(collectionNames[c]))
	    .pipe(uglify())
	    .pipe(gulp.dest(collectionPath))
		.pipe(checkFilesize());

  }  
  return stream;
  
});

gulp.task('report-min', function () {
    return gulp.src('cmdbuild/collection/*.min.js')
        .pipe(sizereport({
            gzip: true
        }));
});

gulp.task('report-vanyl', function () {
	var allScripts = [];
	for (var c in collectorLookup) {
		var curr = collectorLookup[c];
		for (var s in curr){
			var that = curr[s];
			allScripts.push(that);
		}
	}

	return gulp.src(allScripts)
	  	.pipe(sizereport({
	  		gzip: true
	  	}));
});


